### ISSUE TITLE
Chyba?

### ISSUE THREAD

**Issue by djlucas123456** [krejcipetr/sledovanitv#1]
Zdravim.. dneska jsem vyzkousel.. mel jsem prvotni problemy se zprovoznenim.. kdy jsem musel vepsat rucne prihlaseni do souboru a obnovit token.. po namapovani jsem testoval jeden program Nova ovsem v kodi jsem mel problem pri prvnim pustenim ze mi jel zvuk a obraz ne napodruhe uz jel i obraz.. ve VLC na Macu jsem tenhle problem nezaznamenal jen to poprve dele nacitalo.. u palinkova reseni pvr se mi nekdy stava ze obraz najede za nejakou sekundu zatimco zvuk uz jede.. tenhle problem mam jen u sledovanitv jinde ho nemam...

**Comment by krejcipetr** [comment]
Problem s TVH 4.2, viz clanky na inetu.

U TVH 4.3 uz udelali nejakou opravu a vypadavani je sporadicky.
